services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=analyzer_db
    ports:
      - "5433:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  cpp-engine:
    build:
      context: ./cpp-core
      dockerfile: dockerfile
    volumes:
      - ./cpp-core:/app/cpp-core
      - ./proto:/app/proto
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    environment:
      - DB_CONNECTION=postgresql://user:pass@db:5432/analyzer_db
      - REDIS_HOST=redis

  php-app:
    build:
      context: ./php-app
    volumes:
      - ./php-app:/var/www/html
      - ./proto:/app/proto
    depends_on:
      - db
      - cpp-engine

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./php-app:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-app